storage:
  bucketNames:
    chunks: chunks
    ruler: ruler
    admin: admin
  type: s3
  s3:
    s3: <WHAT SHOULD GO HERE?>
    endpoint: <endpoint>
    region: <AWS region>
    secretAccessKey: <AWS secret access key>
    accessKeyId: <AWS access key ID>
    s3ForcePathStyle: false
    insecure: false